version: '3'

services:
    server:
        restart: unless-stopped
        build: ./server
        ports:
            - "8080:80"
            - "8443:443"
        depends_on:
            - db
        environment:
            POSTGRES_CONNECTION_STRING: "Host=db;Database=rpiss;Username=rpiss;Password=rpiss"
    db:
        image: postgres:11
        environment:
            POSTGRES_DB: "rpiss"
            POSTGRES_USER: "rpiss"
            POSTGRES_PASSWORD: "rpiss"
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
  db-data:
